### ISSUE TITLE
Data Store usage for AdaptiveIndexDefrag

### ISSUE THREAD

**Issue by d-moloney** [microsoft/tigertoolbox#102]
AdaptiveIndexDefrag
When Query Store is used on a very large database with over 10,000 tables database, this routine causes an extremely large amount of records in the Query Store Plan table.   My database has over 100,000 statistics and the way this routine runs is it generates a new plan for each statistic when the statistic is being gathered because its not using variables but the actual value. 

It appears that when the routine runs it runs this command for each statistic. 

SELECT @rowmodctr_Out = ISNULL(modification_counter,0), @rows_Out = ISNULL(rows,0), @rows_sampled_Out = ISNULL(rows_sampled,0) FROM sys.dm_db_stats_properties(418373551,6)"

I wish this used variable instead of the actual value (in this case 418373551,6) when running the select statement so the query store doesn't have to store each one of the queries.

**Comment by pmasl** [comment]
This is fair, will keep in backlog. Feel free to submit a pull request in case you want to tackle it yourself

**Comment by pmasl** [comment]
Actually, uploading the change with v1.6.6.8 in a few minutes
