### ISSUE TITLE
Issue with backups check,  #tmpdbs_userchoice  and @dbScope in Check_BP_Servers.sql

### ISSUE THREAD

**Issue by eldarkt** [Microsoft/tigertoolbox#104]
with all default parameters (except SET @ptochecks = 0) the "Backup checks" doesn't really work because #tmpdbs_userchoice is not filled when @dbscope is not set (by default), line 2067:

IF @dbScope IS NOT NULL
BEGIN
	SELECT @sqlcmd = 'SELECT [dbid], [dbname] 
FROM #tmpdbs0 (NOLOCK) 
WHERE is_read_only = 0 AND [state] = 0 AND [dbid] > 4 AND is_distributor = 0
	AND [role] <> 2 AND (secondary_role_allow_connections <> 0 OR secondary_role_allow_connections IS NULL)
	AND [dbid] IN (' + REPLACE(@dbScope,' ','') + ')'
	
	INSERT INTO #tmpdbs_userchoice ([dbid], [dbname])
	EXEC sp_executesql @sqlcmd;

	SELECT @sqlcmd = 'DELETE FROM #tmpdbs1 WHERE [dbid] NOT IN (' + REPLACE(@dbScope,' ','') + ')'
	EXEC sp_executesql @sqlcmd;
END;

Later this table is joined for checks (for example, 4961 and 4969 lines):
INNER JOIN #tmpdbs_userchoice tuc ON b.database_name = tuc.[dbname]
and thus returns an empty resultset.

To "fix" it, I have added that from 2082 line:

--fix
ELSE 
BEGIN
SELECT @sqlcmd = 'SELECT [dbid], [dbname] 
FROM #tmpdbs0 (NOLOCK) 
WHERE is_read_only = 0 AND [state] = 0 AND [dbid] > 4 AND is_distributor = 0
	AND [role] <> 2 AND (secondary_role_allow_connections <> 0 OR secondary_role_allow_connections IS NULL)'
		
	INSERT INTO #tmpdbs_userchoice ([dbid], [dbname])
	EXEC sp_executesql @sqlcmd;
END;
--fix

Screenshot with the difference attached (after "|-Starting Backup checks" row), left is the "fixed" version.
I am not sure that this "fix" is perfect, could you please check that.
Thanks!

![image](https://user-images.githubusercontent.com/21364497/48117444-52edbe00-e27a-11e8-961f-d3d2686c15af.png)

**Comment by pmasl** [comment]
Thanks, this had been merged and fixed
