### ISSUE TITLE
Support for resumable index rebuilds

### ISSUE THREAD

**Issue by KuehneThomas** [Microsoft/tigertoolbox#108]
Would it be possible to support also the resumable feature in the AdaptiveIndexDefrag script?
https://github.com/Microsoft/tigertoolbox/tree/master/AdaptiveIndexDefrag

Feature:
https://docs.microsoft.com/de-de/sql/t-sql/statements/alter-index-transact-sql?view=sql-server-2017

It has been considered in the source for the script:
https://github.com/olahallengren/sql-server-maintenance-solution/blob/master/IndexOptimize.sql

**Comment by DRed96** [comment]
First time contributing, I am not sure if this is the appropiate place to post this or if I should open a new issue.

In the commit https://github.com/KuehneThomas/tigertoolbox/commit/faaed0f3f62f78919755bc255f900bbce4570ef5

The following operation is used: `sys.index_resumable_operations`.

I believe that this operation was introduced in SQL 2017 [link](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-index-resumable-operations?view=sql-server-2017) . Therefore making the script incompatible with previous versions.

**Comment by pmasl** [comment]
Please test with the latest version. Apologies for the delayed response.
