### ISSUE TITLE
Leading number in database name causes error 102

### ISSUE THREAD

**Issue by hitzand** [Microsoft/tigertoolbox#11]
I have a database with an unfortunate name like '4u2defag'.  Calling usp_AdaptiveIndexDefrag using @dbScope of N'4u2defag' creates a command like 
`ALTER INDEX [cci_s_poltran] ON 4u2defag.[dbo].[STG_POLICYTRANSACTION] REORGANIZE;`

This causes an error: 

>  Error 102 has occurred. Message: Incorrect syntax near '4'.

Calling usp_AdaptiveIndexDefrag  using @dbScope of N'[4u2defag]' fails.

**Comment by pmasl** [comment]
Thanks for the update. I'll issue a new update later today.

**Comment by pmasl** [comment]
Fixed in v1.6.3.2
