### ISSUE TITLE
The parameterized query '(@maxservermemIN bigint, @minservermemIN bigint, @systemmemIN bi' expects the parameter '@minservermemIN', which was not supplied.

### ISSUE THREAD

**Issue by mike-halford** [microsoft/tigertoolbox#111]
Since upgrading from v2.2.2 to v2.2.3.4 I'm getting this error

Msg 8178, Level 16, State 1, Line 0
The parameterized query '(@maxservermemIN bigint, @minservermemIN bigint, @systemmemIN bi' expects the parameter '@minservermemIN', which was not supplied.

**Comment by pmasl** [comment]
Does it repro in the newer version? If so which SQL version is this?

**Comment by mike-halford** [comment]
Cannot repro with new version.

**Comment by mike-halford** [comment]
Cannot repro with new version.
