### ISSUE TITLE
sys.configurations setting MaxDop(max degree of parallelism) Algorithm needs updated

### ISSUE THREAD

**Issue by sm8680** [Microsoft/tigertoolbox#129]
MaxDop algorithm in file 0_database_server_options.sql should be updated to match the MaxDop algorithm found in Check_BP_Servers.sql that provides a best practices configuration check.

**Comment by pmasl** [comment]
Thanks, updating now for MaxDOP and MaxMem.

**Comment by sm8680** [comment]
Hi Pedro I was curious lets say we small sized machine and we have a numa of 1 with 4 CPU's.  The previous algorithm would of resulted in 0.  The updated algorithm will result in the first case statement and be set to 4.  Now in this case 0 and 4 are the pretty much the same thing.  0 can mean up to 64 but in our case it will be up to 4.   Is their a reason why you are setting it to 4 and not 0?  I'm just trying to make sure I'm not missing anything.

Keep in mind let's say a Virtual Machine expert decides to add anywhere between 2-4 CPUs.  But they don't tell the DBA team to reconfigure SQL Server.  Leaving the setting to 0 will allow for more processors to be used per say.  But then the adverse affect could of been that setting it to 4 initially was the best setting going forward regardless of augmentation based on stress testing and adding capacity.

**Comment by pmasl** [comment]
HI, in a nutshell, your observation is correct here:
The updated algorithm will result in the first case statement and be set to 4. Now in this case 0 and 4 are the pretty much the same thing. 0 can mean up to 64 but in our case it will be up to 4. Is their a reason why you are setting it to 4 and not 0?

I see you other point though. It is a risk for hot-add for non-numa architectures only. Let me think about thia.
