### ISSUE TITLE
Error view_Running_Blocked_processes (DMV: sys.dm_exec_function_stats) on (SS2012 and SS2014)

### ISSUE THREAD

**Issue by sm8680** [Microsoft/tigertoolbox#130]
In the section of code that mentions function stats.

-- Function stats
If @sqlmajorver >= 11  -- 11 needs to be changed to 13
.
.
sys.dm_exec_function_stats  --> This DMV was introduced in SQL Server 2016. 

-- Code will error for SS2012 and SS2014 due to the above DMV.

-- I've turned this into a stored procedure.  Also created an @Advanced variable.  That defaults to N when set to Y will run your commented code that I've uncommented.  
Small portion of the code below.  I thought about adding  sp_blocker_pss08(to the if statement below but decided against this could be overkill.)

	 SELECT * 
	 FROM master.sys.sysprocesses with(nolock)
	 WHERE blocked = 0 AND spid IN (SELECT blocked FROM master.sys.sysprocesses WHERE blocked <> 0)

	 IF @@ROWCOUNT > 0  -- Will only execute the following 2 sprocs if blocking is occurring.
	    BEGIN
		  EXECUTE dbo.sp_WhoIsActive @find_block_leaders = 1, @get_plans = 2
		  EXECUTE dbo.Running_Blocked_processes @Advanced = @Advanced
            END

I love what the team is doing.  Continuous quality improvement helps to better process and identify issues in production for evaluation.

**Comment by pmasl** [comment]
Thanks, merged a fix now
