### ISSUE TITLE
[AdaptiveIndexDefrag] Invalid object name 'sys.index_resumable_operations' (SS2014)

### ISSUE THREAD

**Issue by mappao** [Microsoft/tigertoolbox#131]
Running usp_AdaptiveIndexDefrag with all default parameters stops with following error:
Msg 208, Level 16, State 1, Procedure usp_AdaptiveIndexDefrag, Line 1684 [Batch Start Line 9]
Invalid object name 'sys.index_resumable_operations'.

FYI, @sqlmajorver = 12, @sqlminorver = 0, @sqlbuild = 6024

Thank you.

**Comment by d-moloney** [comment]
I am getting the same error SQL server 13.0.5292

**Comment by Zek99** [comment]
same issue, please consider using the `@sqlmajorver` variable you have within the script.

**Comment by pmasl** [comment]
Please test with the latest version. Apologies for the delayed response.
