### ISSUE TITLE
usp_whatsup - version check before dm_exec_function_stats is incorrect

### ISSUE THREAD

**Issue by DaveDustin** [Microsoft/tigertoolbox#133]
https://github.com/Microsoft/tigertoolbox/blob/c8e8211bb3d9e5311ad435ebe8d882c28c9df282/usp_WhatsUp/usp_whatsup.sql#L591

`sys.dm_exec_function_stats` was introduced in SQL2016 (13) but the version check is set to 11 (2012)

**Comment by pmasl** [comment]
Thanks, this is fixed now.
