### ISSUE TITLE
Check_BP_Servers.sql

### ISSUE THREAD

**Issue by FifthMan** [Microsoft/tigertoolbox#138]
**1.  sqlserver 2014 or earlier, remove below scripts when CREATE PROCEDURE bp_check :**
IF @recommendationsNum > 0
BEGIN

	WITH CTE_Tunning
AS (SELECT tr.reason,tr.score, pln.query_id, pln.regressedPlanId, pln.recommendedPlanId,
           JSON_VALUE(tr.state,'$.currentValue') AS CurrentState,
           JSON_VALUE(tr.state,'$.reason') AS CurrentStateReason,
           JSON_VALUE(tr.details,'$.implementationDetails.script') AS ImplementationScript
    FROM sys.dm_db_tuning_recommendations AS tr
        CROSS APPLY
        OPENJSON(tr.details,'$.planForceDetails')
        WITH (query_id INT '$.queryId',
              regressedPlanId INT '$.regressedPlanId',
              recommendedPlanId INT '$.recommendedPlanId') AS pln)
SELECT 'Information' AS [Category], 'Tuning_recommendations' AS [Information], 
		qsq.query_id,
       cte.reason,
       cte.score,
       cte.CurrentState,
       cte.CurrentStateReason,
       qsqt.query_sql_text,
       CAST(rp.query_plan AS XML) AS RegressedPlan,
       CAST(sp.query_plan AS XML) AS SuggestedPlan,
       cte.ImplementationScript
FROM CTE_Tunning  AS cte
    JOIN sys.query_store_plan AS rp
        ON rp.query_id = cte.query_id
           AND rp.plan_id = cte.regressedPlanId
    JOIN sys.query_store_plan AS sp
        ON sp.query_id = cte.query_id
           AND sp.plan_id = cte.recommendedPlanId
    JOIN sys.query_store_query AS qsq
        ON qsq.query_id = rp.query_id
    JOIN sys.query_store_query_text AS qsqt
        ON qsqt.query_text_id = qsq.query_text_id;

END;

**2. Starting Indexing per Table, Ambiguous column name 'index_id', modify as below:**
SET @sqlcmd = 'USE ' + QUOTENAME(@dbname) + ';
SELECT 1 AS [Check], ' + CONVERT(VARCHAR(8), @dbid) + ', ''' + REPLACE(@dbname, CHAR(39), CHAR(95)) + ''',	
s.name, t.name, SUM(P.rows)
FROM sys.indexes AS si (NOLOCK)
INNER JOIN sys.tables AS t (NOLOCK) ON si.[object_id] = t.[object_id]
INNER JOIN sys.schemas AS s (NOLOCK) ON s.[schema_id] = t.[schema_id]
INNER JOIN sys.partitions p (NOLOCK) ON  si.[object_id]=p.[object_id] and si.[index_id]=p.[index_id]
WHERE si.is_hypothetical = 0
GROUP BY si.[object_id], t.name, s.name
HAVING COUNT(**si.index_id**) = 1 AND MAX(**si.index_id**) = 0
UNION ALL
SELECT 2 AS [Check], ' + CONVERT(VARCHAR(8), @dbid) + ', ''' + REPLACE(@dbname, CHAR(39), CHAR(95)) + ''',	
s.name, t.name, SUM(P.rows)
FROM sys.indexes AS si (NOLOCK) 
INNER JOIN sys.tables AS t (NOLOCK) ON si.[object_id] = t.[object_id]
INNER JOIN sys.schemas AS s (NOLOCK) ON s.[schema_id] = t.[schema_id]
INNER JOIN sys.partitions p (NOLOCK) ON  si.[object_id]=p.[object_id] and si.[index_id]=p.[index_id]
WHERE si.is_hypothetical = 0
GROUP BY t.name, s.name
HAVING COUNT(**si.index_id**) > 1 AND MIN(**si.index_id**) = 0;'

**Comment by pmasl** [comment]
Fixed the 1st without removing, and fixed the 2nd as you mentioned. Merging now.
