### ISSUE TITLE
Intermittent issue - XML - SQL 2016

### ISSUE THREAD

**Issue by mjkirkpatrick** [microsoft/tigertoolbox#150]
Using latest version:

EXEC master.dbo.usp_whatsup @sqluptime = 0,
                            @requests = 1,
                            @blocking = 0,
                            @spstats = 0,
                            @qrystats = 0,
                            @trstats = 0,
                            @fnstats = 0,
                            @top = 100;

Msg 6841, Level 16, State 1, Line 13
FOR XML could not serialize the data for node 'text()' because it contains a character (0x0000) which is not allowed in XML. To retrieve this data using FOR XML, convert it to binary, varbinary or image data type and use the BINARY BASE64 directive.

**Comment by pmasl** [comment]
Let's please track this in bug #140  https://github.com/microsoft/tigertoolbox/issues/140
