### ISSUE TITLE
Check_BP_Servers runaway on SQL Server 2012 SP3 CU6 - Invalid column name 'is_auto_create_stats_incremental_on'

### ISSUE THREAD

**Issue by yamezui** [Microsoft/tigertoolbox#18]
When running BP Check script V2.1.5 on a SQL Server 2012 SP3 instance the following error occurred and the script never end:

**|-Starting User DBs with non-default options
Msg 207, Level 16, State 1, Line 6
Invalid column name 'is_auto_create_stats_incremental_on'.**

When looking at sys.dm_exec_request the script has status running, blocking_session_id 0 ,last_wait_type SOS_SCHEDULER_YIELD

**Comment by pmasl** [comment]
The fix is available since Nov-23 in v2.1.5.1. Please use that one instead. Thank you.
