### ISSUE TITLE
It's unsafe to WMI query Win32_Product in the TLS 1.2 script

### ISSUE THREAD

**Issue by codykonior** [Microsoft/tigertoolbox#20]
People shouldn't run this script on servers - querying that class makes [Windows Installer run reconfigure on every installed application][1], which can lead to downtime.

I think leaving it in the script like that will catch some people off guard.

[1]: https://support.microsoft.com/en-us/kb/974524

**Comment by amitmsft** [comment]
Thanks for reporting this. I have changed the script to use Win32reg_AddRemovePrograms instead.
