### ISSUE TITLE
Should 2048KB be added to NTFS block size in volumes that hold database files <> 64KB subsection?

### ISSUE THREAD

**Issue by alexprotsenko** [microsoft/tigertoolbox#211]
Hi @pmasl. Windows Server 2019 presents greater block sizes in comparison to the previous versions - up to 2048KB. Should the NTFS block size in volumes that hold database files <> 64KB subsection be updated to take this into account?

**Comment by pmasl** [comment]
Whether or not we should might be up for discussion at some time, but there aren't changes in the engine to warrant immediate reevaluation of the best practice you mention - the read-ahead logic is the same, driven by extents which are 64KB.

**Comment by alexprotsenko** [comment]
@pmasl, appreciate your fast response
