### ISSUE TITLE
TLS 1.2: Win32Reg_AddRemovePrograms only available if using SCCM

### ISSUE THREAD

**Issue by modsqlguy** [Microsoft/tigertoolbox#22]
Unfortunately, it appears Win32Reg_AddRemovePrograms is only available if SCCM is installed.

Per https://blogs.technet.microsoft.com/heyscriptingguy/2011/11/13/use-powershell-to-quickly-find-installed-software/ ... querying the registry may be a solution.

**Comment by amitmsft** [comment]
Thank you for reporting this issue. I have corrected the script to use your suggestion and also provided attribution in the comments! :)
