### ISSUE TITLE
TLS 1.2: function Check-Sqlncli 

### ISSUE THREAD

**Issue by modsqlguy** [Microsoft/tigertoolbox#23]
The Check-Sqlncli function uses "-eq 50" to filter for 2008 R2 Native Client. This will cause false positive "TLS 1.2 supported" messages for 2008 R2 patch levels that do not support TLS 1.2 like the one below:

DisplayName: Microsoft SQL Server 2008 R2 Native Client 
DisplayVersion: 10.51.2796.0

**Comment by amitmsft** [comment]
Thank you for reporting the issue. This has been corrected in the latest issue. Please feel free to edit in the future and submit a PULL request in the future if you find any further issues. We love receiving contributions from the community.
