### ISSUE TITLE
Cleaner version check

### ISSUE THREAD

**Issue by hcc1187** [Microsoft/tigertoolbox#30]
Hey Amit,
 :thumbsup: Thanks for the ps script.
Just a syntactic sugar that you can check the versions by:
```javascript
if ([version]$cli.DisplayVersion -lt [version]"11.0.6538")
```
Also line 35 and 39 should be:
```javascript
$cli.DisplayVersion
```

**Comment by amitmsft** [comment]
Please feel free to submit a PULL request for the suggested changes. :)
