### ISSUE TITLE
Collation and error convertion issue

### ISSUE THREAD

**Issue by DBAlberto** [Microsoft/tigertoolbox#31]
I encountered with 2 minor issues, 

Collation issue: 
Current: WHERE feature_name IN ('ColumnStoreIndex','InMemoryOLTP')
New:     WHERE Feature_Name IN ('ColumnStoreIndex','InMemoryOLTP')
Current: SET distinctCnt = @distinctCnt, OptimBucketCnt = @OptimBucketCnt, isdone = 1
New:     SET DistinctCnt = @distinctCnt, OptimBucketCnt = @OptimBucketCnt, isdone = 1
Current: WHERE total_bucket_count > distinctCnt
New:     WHERE total_bucket_count > DistinctCnt
Current: distinctCnt AS [distinct_keys], 
New:     DistinctCnt AS [distinct_keys], 
Current: WHERE total_bucket_count > distinctCnt
New:     WHERE total_bucket_count > DistinctCnt
Current: WHERE total_bucket_count < distinctCnt
New:     WHERE total_bucket_count < DistinctCnt
I am using Modern_Spanish_CS_AS
------------------------
error convertion:
Current: WHEN @sqlmajorver >= 11 AND @winver <= 6.0 AND @accntrsservice <> 'NT AUTHORITY\NETWORKSERVICE' THEN '[INFORMATION: SQL Server Reporting Services is not running with the default account]'
New:     WHEN @sqlmajorver >= 11 AND CONVERT(DECIMAL(3,1), @winver) <= 6.0 AND @accntrsservice <> 'NT AUTHORITY\NETWORKSERVICE' THEN '[INFORMATION: SQL Server Reporting Services is not running with the default account]'

Current: WHEN @clustered = 0 AND @sqlmajorver >= 11 AND @winver <= 6.0 AND @accntolapservice <> 'NT AUTHORITY\NETWORKSERVICE' THEN '[INFORMATION: SQL Server Analysis Services is not running with the default account]'
New:     WHEN @clustered = 0 AND @sqlmajorver >= 11 AND CONVERT(DECIMAL(3,1), @winver) <= 6.0 AND @accntolapservice <> 'NT AUTHORITY\NETWORKSERVICE' THEN '[INFORMATION: SQL Server Analysis Services is not running with the default account]'
I am using SQL Server 2016 - 13.0.4001.0

BTW thanks for sharing this great tool
[Check_BP_Servers.zip](https://github.com/Microsoft/tigertoolbox/files/811574/Check_BP_Servers.zip)

**Comment by pmasl** [comment]
Thanks for finding these. Fixed in the new uploaded version.
