### ISSUE TITLE
Running-Blocked-Processes script, in [running_statement] column, last two symbols lost

### ISSUE THREAD

**Issue by eldarkt** [Microsoft/tigertoolbox#32]
To prevent this, I suggest to change this parts:

SUBSTRING(qt2.text,
		(CASE WHEN er.statement_start_offset = 0 THEN 0 ELSE er.statement_start_offset/2 END),
		(CASE WHEN er.statement_end_offset = -1 THEN DATALENGTH(qt2.text) ELSE er.statement_end_offset/2 END - (CASE WHEN er.statement_start_offset = 0 THEN 0 ELSE er.statement_start_offset/2 END))),

to this:

SUBSTRING(qt2.text,
		**1+**(CASE WHEN er.statement_start_offset = 0 THEN 0 ELSE er.statement_start_offset/2 END),
		**1+**(CASE WHEN er.statement_end_offset = -1 THEN DATALENGTH(qt2.text) ELSE er.statement_end_offset/2 END - (CASE WHEN er.statement_start_offset = 0 THEN 0 ELSE er.statement_start_offset/2 END))),

as described here:
https://msdn.microsoft.com/en-us/library/ms181929.aspx (Example B)

**Comment by pmasl** [comment]
Thanks for finding this, will be updated in a few minutes.
