### ISSUE TITLE
For Performance Baseline, missing sproc

### ISSUE THREAD

**Issue by gturner1956** [Microsoft/tigertoolbox#33]
Hi,

I downloaded and installed SQL Performance Baseline which created a new database, objects and jobs to gather and collect performance data to run the SSRS reports.

However, one of the jobs (Load SystemHealthSession) is missing the sproc spLoadSystemHealthSession to execute.   I don't see it anywhere in the install package.   

Am I missing something?

Thanks.

**Comment by savjani** [comment]
You need to run CreateSystemhealthDBAndSchema.sql from the solution to create the sproc spLoadSystemHealthSession
