### ISSUE TITLE
SQL Performance Baselining Reports > SQL Performance Dashboard reports shows No Data Available

### ISSUE THREAD

**Issue by gkieffer83** [Microsoft/tigertoolbox#35]
This is explained by the following query returning NULL values except for the Data and Time columns:
exec sp_executesql N'SELECT 
Date,[Time],
[buffer manager\page life expectancy] AS ''Page Life Expectancy'',
[buffer manager\buffer cache hit ratio] AS ''Buffer Cache Hit Ratio'',
ROUND([memory manager\target server memory (kb)]/1024.0/1024.0,0) AS ''Target Server Memory'',
ROUND([memory manager\total server memory (kb)]/1024.0/1024.0,0) AS ''Total Server Memory'',
ROUND([memory\available mbytes]/1024.0,0) AS ''Available Memory'',
[buffer manager\checkpoint pages/sec] AS ''Checkpoint Pages per sec'',
[buffer manager\lazy writes/sec] AS ''Lazy Writes per sec'',
[Buffer Manager\Free pages] AS ''Free pages'',
ROUND([transactions\free space in tempdb (kb)]/1024.0/1024.0,0) AS ''Tempdb Free Space in GB''
FROM
(
SELECT     CounterName, 
CONVERT(varchar(20),DateSampled,101) as ''Date'',
LEFT(CONVERT(varchar(20),DateSampled,8),5) as ''Time'', 
DATEPART(mi, DateSampled) AS ''Minute'', 
ROUND(CounterValue,0) AS ''CounterValue''
FROM         PerformanceCounter
WHERE     (CounterName like ''%buffer manager\page life expectancy%'' or CounterName like ''%buffer manager\buffer cache hit ratio%'' or CounterName like''%memory manager\target server memory (kb)%'' or CounterName like ''%memory manager\total server memory (kb)%'' or CounterName like ''%buffer manager\checkpoint pages/sec%'' or CounterName like ''%buffer manager\lazy writes/sec%'' or CounterName like ''%Buffer Manager\Free pages%'' or CounterName like ''%transactions\free space in tempdb (kb)%'' or CounterName like ''%memory\available mbytes%'' or CounterName like ''%buffer manager\page life expectancy%'') 
and DateSampled between @StartDate and @EndDate
) as p
PIVOT 
(
AVG(CounterValue)
FOR 
CounterName IN ([buffer manager\page life expectancy],
									[buffer manager\buffer cache hit ratio],
									[memory manager\target server memory (kb)],
									[memory manager\total server memory (kb)],
									[memory\available mbytes],
									[buffer manager\checkpoint pages/sec],
									[buffer manager\lazy writes/sec],
									[Buffer Manager\Free pages],
									[transactions\free space in tempdb (kb)])
) AS pivottable
ORDER by [Time]',N'@StartDate nvarchar(18),@EndDate nvarchar(18)',@StartDate=N'4/17/2017 00:01:00',@EndDate=N'4/18/2017 23:59:59'

**Comment by gkieffer83** [comment]
Reason was that it works for a default instance but not for a named instance.
I've rewritten the stored proc and it's now working for both:

USE [dba_local]
GO
/****** Object:  StoredProcedure [dbo].[spGetPerfCountersFromPowerShell]    Script Date: 19/Apr/17 1:58:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Adrian Sullivan, af.sullivan@outlook.com
-- Create date: 2016/12/12
-- Description:	Taking away the need for PS1 files and script folder
-- =============================================
ALTER PROCEDURE [dbo].[spGetPerfCountersFromPowerShell]
AS
BEGIN

		DECLARE @syscounters NVARCHAR(4000)
	SET @syscounters=STUFF((SELECT DISTINCT ''',''' +LTRIM([counter_name])
	FROM [dba_local].[dbo].[PerformanceCounterList]
	WHERE [is_captured_ind] = 1 FOR XML PATH('')), 1, 2, '')+'''' 

	DECLARE @cmd NVARCHAR(4000)
	DECLARE @syscountertable TABLE (id INT IDENTITY(1,1), [output] VARCHAR(500))
	DECLARE @syscountervaluestable TABLE (id INT IDENTITY(1,1), [value] VARCHAR(500))

	SET @cmd = 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe "& get-counter -counter '+ @syscounters +' | Select-Object -ExpandProperty Readings"'
	INSERT @syscountertable
	EXEC master..xp_cmdshell @cmd

	declare @sqlnamedinstance sysname
	declare @networkname sysname
	if (select CHARINDEX('\',@@SERVERNAME)) = 0
	begin
	INSERT [dba_local].[dbo].[PerformanceCounter] (CounterName, CounterValue, DateSampled)
	SELECT  REPLACE(REPLACE(REPLACE(ct.[output],'\\'+@@SERVERNAME+'\',''),' :',''),'sqlserver:','')[CounterName] , CONVERT(varchar(20),ct2.[output]) [CounterValue], GETDATE() [DateSampled]
	FROM @syscountertable ct
	LEFT OUTER JOIN (
	SELECT id - 1 [id], [output]
	FROM @syscountertable
	WHERE PATINDEX('%[0-9]%', LEFT([output],1)) > 0  
	) ct2 ON ct.id = ct2.id
	WHERE  ct.[output] LIKE '\\%'
	ORDER BY [CounterName] ASC
	end
	else
	begin
	select @networkname=RTRIM(left(@@SERVERNAME, CHARINDEX('\', @@SERVERNAME) - 1))
	select @sqlnamedinstance=RIGHT(@@SERVERNAME,CHARINDEX('\',REVERSE(@@SERVERNAME))-1)
	INSERT [dba_local].[dbo].[PerformanceCounter] (CounterName, CounterValue, DateSampled)
	SELECT  REPLACE(REPLACE(REPLACE(ct.[output],'\\'+@networkname+'\',''),' :',''),'mssql$'+@sqlnamedinstance+':','')[CounterName] , CONVERT(varchar(20),ct2.[output]) [CounterValue], GETDATE() [DateSampled]
	FROM @syscountertable ct
	LEFT OUTER JOIN (
	SELECT id - 1 [id], [output]
	FROM @syscountertable
	WHERE PATINDEX('%[0-9]%', LEFT([output],1)) > 0  
	) ct2 ON ct.id = ct2.id
	WHERE  ct.[output] LIKE '\\%'
	ORDER BY [CounterName] ASC
	end
END

**Comment by savjani** [comment]
Thanks @gkieffer83 !!! I have merged your change into the solution.
