### ISSUE TITLE
Running PowerShell cmd in Command Window returns specified counter not found error

### ISSUE THREAD

**Issue by tgspacelabs** [Microsoft/tigertoolbox#36]
C:\Windows\system32>C:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe "& get-counter -counter '\LogicalDisk(*)\Avg. Disk Queue Length','\LogicalDisk(*)\Avg. Disk sec/Read','\LogicalDisk(*)\Avg. Disk sec/Transfer','\LogicalDisk(*)\Avg. Disk sec/Write','\LogicalDisk(*)\Current Disk Queue Length','\Memory\Available MBytes','\Paging File(*)\*','\Process(sqlservr)\% Privileged Time','\Process(sqlservr)\% Processor Time','\Processor(_Total)\% Privileged Time','\Processor(_Total)\% Processor Time','\SQLServer:Buffer Manager\Buffer cache hit ratio','\SQLServer:Buffer Manager\Checkpoint Pages/Sec','\SQLServer:Buffer Manager\Free Pages','\SQLServer:Buffer Manager\Lazy Writes/Sec','\SQLServer:Buffer Manager\Page life expectancy','\SQLServer:General Statistics\User Connections','\SQLServer:Memory Manager\Target Server Memory (KB)','\SQLServer:Memory Manager\Total Server Memory (KB)','\SQLServer:SQL Statistics\Batch Requests/sec','\SQLServer:SQL Statistics\SQL Compilations/sec','\SQLServer:SQL Statistics\SQL Re-Compilations/sec','\SQLServer:Transactions\Free Space in tempdb (KB)' | Select-Object -ExpandProperty Readings"
Get-Counter : The specified counter could not be found.
At line:1 char:1
+ & get-counter -counter '\LogicalDisk(*)\Avg. Disk Queue Length','\Log ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (:) [Get-Counter], Exception
    + FullyQualifiedErrorId : CounterApiError,Microsoft.PowerShell.Commands.GetCounterCommand

Traced in down to the counter:

C:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe "& get-counter -counter **'\SQLServer:Buffer Manager\Free Pages'** | Select-Object -ExpandProperty Readings"

**Comment by gkieffer83** [comment]
Hi,
I traced it down to the same counter and this is due to the fact that this counter doesn't exist anymore, since SQL 2012. 
https://blogs.msdn.microsoft.com/vsanil/2012/11/21/did-some-performance-counters-like-free-pages-disappear-in-sql-2012/
