### ISSUE TITLE
Missing dbo.spLoadSystemHealthSession

### ISSUE THREAD

**Issue by jlent01** [Microsoft/tigertoolbox#38]
When running 'Load SystemHealthSession' agent job the following error message is received.
Could not find stored procedure 'dbo.spLoadSystemHealthSession'. [SQLSTATE 42000] (Error 2812).  The step failed.

dbo.spLoadSystemHealthSession does not exist in the dba_local database and doesn't appear to be present in the createobjects.sql file.

**Comment by DiHo78** [comment]
Quite easy: you need to run this script as well
https://github.com/Microsoft/tigertoolbox/blob/master/SQL-Performance-Baseline/CreateSystemhealthDBAndSchema.sql

**Comment by jlent01** [comment]
Thanks, just saw the previous issue.
