### ISSUE TITLE
Error converting data type varchar to float when running report

### ISSUE THREAD

**Issue by DiHo78** [Microsoft/tigertoolbox#41]
Hi all,

as I have  already mentioned in https://github.com/Microsoft/tigertoolbox/issues/34 
some people will get a subsequent error when they use the conversion of the Performance Counter Output to varchar (20) inside the stored procedure spGetPerfCountersFromPowershell.

If you have a system which uses a comma instead of a point to mark your decimal place, then you will (of course) save your perf Counter values inside the table dba_local.dbo.CounterValue also with commas instead of points.
This leads to "Error converting data type varchar to float".
I have picked up the query the dashboard report uses:

exec sp_executesql N'DECLARE @CPUCOUNT int
SELECT @CPUCOUNT=cpu_count from sys.dm_os_sys_info
SELECT 
Date,
ROUND([processor(_total)\% processor time],0) as ''Processor Utilization'',
ROUND(([processor(_total)\% privileged time]*[processor(_total)\% processor time])/100,0) as ''Priviledged Utilization'',
ROUND(([processor(_total)\% processor time]*[process(sqlservr)\% processor time])/100/@CPUCOUNT,0) as ''SQL Utilization'',
ROUND([sql statistics\batch requests/sec],0) as ''Batch Request per second'',
ROUND([sql statistics\sql compilations/sec],1) as ''SQL Compilations per second'',
ROUND([sql statistics\sql re-compilations/sec],1) as ''SQL Recompilations per second'',
ROUND([General Statistics\User Connections],0) as ''User Connections'',
ROUND([logicaldisk(_total)\avg. disk sec/read]*1000.0,1) AS ''Disk Read Latency'', 
ROUND([logicaldisk(_total)\avg. disk sec/write]*1000.0,1) AS ''Disk Write Latency'',
ROUND([memory\available mbytes],0) AS ''Available Memory In MB'',
ROUND([transactions\free space in tempdb (kb)]/1024.0/1024.0,0) AS ''Free Space in Tempdb''
FROM
(
select 
CounterName,
CONVERT(varchar(20),DateSampled,101) as ''Date'',
ROUND(CounterValue,7) as ''CounterValue''
from PerformanceCounter
where CounterName IN (''processor(_total)\% processor time'',''processor(_total)\% privileged time'',''process(sqlservr)\% processor time'',''sql statistics\batch requests/sec'',''sql statistics\sql compilations/sec'',''sql statistics\sql re-compilations/sec'',''General Statistics\User Connections'',''logicaldisk(_total)\avg. disk sec/read'', ''logicaldisk(_total)\avg. disk sec/write'', ''memory\available mbytes'',''transactions\free space in tempdb (kb)'')
and DateSampled between @StartDate and @EndDate

) AS p
PIVOT 
(
AVG(CounterValue)
FOR 
CounterName IN ([processor(_total)\% processor time],[processor(_total)\% privileged time],[process(sqlservr)\% processor time],[sql statistics\batch requests/sec],[sql statistics\sql compilations/sec],[sql statistics\sql re-compilations/sec],[General Statistics\User Connections],[logicaldisk(_total)\avg. disk sec/read], [logicaldisk(_total)\avg. disk sec/write], [memory\available mbytes],[transactions\free space in tempdb (kb)])
) AS pivottable
Order by [Date]',N'@StartDate datetime,@EndDate datetime',@StartDate='2016-11-10 00:00:00',@EndDate='2017-05-10 10:00:00'

I made an adjustment to the EndDate to get data at all because I have set up a "fresh Monitoring".
When running the query I get the error., which is caused by the ROUND() in the sub-select.

So, a point to be discussed:  do you want to fix every Report / query to work around the conversion error or does it make sense to load the data in a suitable format?

Regards
Dirk

**Comment by savjani** [comment]
Dirk,

if we change the format in which we load data, we would still have change the queries in the report to handle the format.

One major change, we should consider it moving all the report queries and convert them into stored procedures in database dba_local. From SSRS report, we can just call the stored procedure which will bring the dataset in the format which report understands. That also gives flexibility in future to modify queries without breaking the report.

I don't have cycles to do it but if someone wants to take a shot, it might be a better approach in my opinion.

Regards,
Parikshit

**Comment by DiHo78** [comment]
Hi Parikshit, 

I am not sure if I can convert the queries quickly to procedures :-)


But maybe I stick to my solution replacing commas with points when pulling the data. 
I'll send you my modified version which I am running successful for a few days now. 
By now no report broke.

Regards Dirk 


Am 10. Mai 2017 19:00:15 MESZ schrieb Parikshit <notifications@github.com>:
>Dirk,
>
>if we change the format in which we load data, we would still have
>change the queries in the report to handle the format.
>
>One major change, we should consider it moving all the report queries
>and convert them into stored procedures in database dba_local. From
>SSRS report, we can just call the stored procedure which will bring the
>dataset in the format which report understands. That also gives
>flexibility in future to modify queries without breaking the report.
>
>I don't have cycles to do it but if someone wants to take a shot, it
>might be a better approach in my opinion.
>
>Regards,
>Parikshit
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Microsoft/tigertoolbox/issues/41#issuecomment-300546867

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by DiHo78** [comment]
Hi Parikshit,

it's me again :-)

let me recap the development of the procedure spGetPerfCountersFromPowerShell
@SQLAdrian  used the following SELECT:
SELECT  REPLACE(REPLACE(REPLACE(ct.[output],''\\''+@@SERVERNAME+''\'',''''),'' :'',''''),''sqlserver:'','''')[CounterName] , CONVERT(MONEY,ct2.[output]) [CounterValue], GETDATE() [DateSampled]

The CONVERT(MONEY...) causes some problems. 
We had the issues reported on GitHub as well as on your Tigerteam blog site: https://blogs.msdn.microsoft.com/sql_server_team/sql-server-performance-baselining-reports-unleashed-for-enterprise-monitoring/

So, one idea is not to convert to money but to varchar(20). This solution actually found it's way to your repository. Change made by @gkieffer83 .

But with this change I ran into subsequent errors.  (Probably other users as well. I'll ask around the PASS Germany community if other experience these problem.)

Therefore my idea is: we take @gkieffer83 solution regarding the named instances but also stick to the conversion to data type money with an additional string replacement.
So it will look similar to this:
SELECT  REPLACE(REPLACE(REPLACE(ct.[output],''\\''+@@SERVERNAME+''\'',''''),'' :'',''''),''sqlserver:'','''')[CounterName] ,  CONVERT( MONEY, replace([ct2].[output], '','', ''.'')) [CounterValue], GETDATE() [DateSampled]

In my eyes this would be a quick win without the need to change the existing reports right now.
What do you think?

Regards,
Dirk

**Comment by savjani** [comment]
Hi @DiHo78,

That sounds like a good plan. Does your previous change which is now merges include this fix. If not, I would suggest you send another pull request with the proposed change and I can test and merge it.

Thanks !!!

Regards,
Parikshit

**Comment by DiHo78** [comment]
Hi Parikshit,

my previous change did not include this fix. So you'll get another pull request.
By now I have two SQL Servers running under Hyper-V on my notebook.  One has my modified version, the other server the original version (e.g. your last commit).

On the mod version I can run the inital report without any problem, the original version again throws 
"System.Data.SqlClient.SqlException: Error converting data type varchar to float."

One thing is important when merging my fix:  at runtime we will convert the perfcounter values to money again. Sometimes it can happen that we get such a low perfcounter value from windows so the system submits the number  with a negative exponent, e.g. E-5   In such a case the agent job will fail with the above mentioned error.  But this is a rare event. On another system I am running this happened only twice in the last 5 days and the scheduler is set to run the job every 5 minutes.  
By now I can deal with this.  

Regards,
Dirk

**Comment by savjani** [comment]
@DiHo78 ,

Can the negative condition be handled in TRY..CATCH block and we skip those values to avoid job to fail and complete gracefully?

**Comment by DiHo78** [comment]
Hi Parikshit,

either we implement the TRY..CATCH block or we update the inserted value afterwards.
The thing is that this value is so small that we could  say it is zero.
And why? Well, in the original version by @SQLAdrian there's the conversion to data type money.
There we have only two decimal places at all. Effectively, when we get a perfcounter value like 8,9999918995165E-05 which should be equal to 0,000089999918995165, then we can determine that the value is 0,00.
Correct me if I am wrong here.

If I find the time, I'll take a look on how to adjust the value in an easy way.

Regards,
Dirk

**Comment by DiHo78** [comment]
Hi again,
a CASE Expression does the trick:

 CASE
                                   WHEN [ct2].[output] LIKE ''%E-%''
                                   THEN ''0''
                                   ELSE CONVERT(MONEY, replace([ct2].[output], '','', ''.''))
                               END AS [CounterValue],

I've created a new branch in my fork. I'll test the modified version a few days and let you know if it works properly.

Regards
Dirk

**Comment by DiHo78** [comment]
Forgot to provide the link:
https://github.com/DiHo78/tigertoolbox/blob/DiHo78-TT-SQLPerformanceBaseline-ProcedureFix/SQL-Performance-Baseline/CREATEOBJECTS.sql

**Comment by SQLAdrian** [comment]
Hi Dirk and Parikshit,

Seems I have been sending pull requests to myself for this. Clearly I don't know how to drive github.

An additional way to safeguard conversion would be to change the PowerShell bit to force conversion to some reasonable decimal, like:
SET @cmd = 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe "& get-counter -counter '+ @syscounters +' -ErrorAction SilentlyContinue | foreach{$_.CounterSamples}| foreach{$_.Path;**''{0:f5}'' -f $_.CookedValue }"**' /*Can also add  +'' ''+  $_.InstanceName*/

Spits out something like:
\\lxlsql2\logicaldisk(_total)\current disk queue length_total
0.00000
\\lxlsql2\memory\available mbytes
1711.00000
\\lxlsql2\paging file(\??\d:\pagefile.sys)\% usage\??\d:\pagefile.sys
58.15185
\\lxlsql2\paging file(\??\d:\pagefile.sys)\% usage peak\??\d:\pagefile.sys
96.62994

@DiHo78, thanks for all your efforts, your changes test fine on my servers. 
Now I shall attempt to get my head around a pull request.

**Comment by DiHo78** [comment]
Hi @SQLAdrian ,

well, in that case you and Parikshit should decide how to go on. Converting to some reasonable decimal will also lead to the decimal Point or decimal comma "issue"´, so at least the replace will still take place.

Regarding the pull requests: I know definitely what you mean.  Had to figure it out a while ago.
Easiest way now for me is:
Keep my fork in sync with the TigerToolBox master.
When doing a Change, creating a branch in my fork. If the fix is fine, request a pull request to Microsoft master. And then apply the request to my own fork as well.

Regards
Dirk
