### ISSUE TITLE
Procedure spLoadScheduleMonitor fails with overflow error

### ISSUE THREAD

**Issue by DiHo78** [Microsoft/tigertoolbox#44]
Hi all,

after running succesful for 18 days the SQL Agent Job "Load SystemHealthSession" fails with the error
"The conversion of the nvarchar value '3632140316' overflowed an int column.
Running the proc dbo.spLoadSystemHealthSession manually provided more Details. The stored procedure spLoadSchedulerMonitor fails.

Msg 248, Level 16, State 1, Procedure spLoadSchedulerMonitor, Line 6 [Batch Start Line 0]
The conversion of the nvarchar value '3632140316' overflowed an int column.

**Comment by DiHo78** [comment]
This high value Comes directly form the ring buffer query. I have already fixed the spLoadSchedulerMonitor proc in one of my branches.  If I find the time I'll test if teh Job is running fine now and the Reports are working

**Comment by DiHo78** [comment]
fix available
https://github.com/DiHo78/tigertoolbox/tree/patch-1

**Comment by savjani** [comment]
Thanks @DiHo78 !!! I have merged your pull request
