### ISSUE TITLE
clarification on datasources for XEventReporting 

### ISSUE THREAD

**Issue by RangaSQL** [Microsoft/tigertoolbox#47]
I see two datasources for the XEReports. For the Performance reports we just provide the SQL Server which has the dba_local database as the datasource. Please confirm what the two datasources should be for the XEventReporting.

BTW...this is a treasure trove! Thanks for sharing this. Many thanks for Parikshit and Tiger team and Pedro for pointing this to me

**Comment by savjani** [comment]
@RangaSQL - I have modified the reports and merged it today. Download the reports again from GitHub and you wont see 2 datasources for the XEReports. There is only one datasource which will be pull data from dba_local for all reports.

Glad you liked the reports. Feel free to contribute back as it is a community effort.
