### ISSUE TITLE
Clarification on the powershell scripts

### ISSUE THREAD

**Issue by RangaSQL** [Microsoft/tigertoolbox#48]
I was able to create the dba_local database, objects and the sql jobs and all is fine. Did not know how the powershell scripts are being used. Please clarify.

**Comment by savjani** [comment]
Powershell scripts are alternative to collect and populate the perfmon data and store it in dba_local. Thanks to @SQLAdrian who published a TSQL stored procedure which avoids the use of powershell script directly in SQL Jobs
