### ISSUE TITLE
BPCheck arithmetic overflow error

### ISSUE THREAD

**Issue by 7gartner** [Microsoft/tigertoolbox#49]
when running against a VLDB (50TB+) we get the following error:

```
  |-Starting Buffer Pool Consumers from Buffer Descriptors
Msg 8115, Level 16, State 2, Line 3
Arithmetic overflow error converting expression to data type int.
```

**Comment by DiHo78** [comment]
Hi @7gartner,
I do not have such a big database but an idea why you get the overflow. 
If you have the time, can you test the following Code?

DECLARE @sqlcmd NVARCHAR(max), @params NVARCHAR(500), @sqlmajorver int
SET @sqlcmd = 'SELECT ''Memory_checks'' AS [Category], ''Buffer_Pool_Consumers'' AS [Information], 
	COUNT_BIG(DISTINCT page_id)*8/1024 AS total_pages_MB, 
	CASE database_id WHEN 32767 THEN ''ResourceDB'' ELSE DB_NAME(database_id) END AS database_name,
	SUM(CONVERT(BIGINT,row_count))/COUNT_BIG(DISTINCT page_id) AS avg_row_count_per_page, 
	SUM(CONVERT(BIGINT, free_space_in_bytes))/COUNT_BIG(DISTINCT page_id) AS avg_free_space_bytes_per_page
	' + CASE WHEN @sqlmajorver >= 12 THEN ',is_in_bpool_extension' ELSE '' END + '
	' + CASE WHEN @sqlmajorver = 10 THEN ',numa_node' ELSE '' END + '
	' + CASE WHEN @sqlmajorver >= 11 THEN ',AVG(read_microsec) AS avg_read_microsec' ELSE '' END + '
FROM sys.dm_os_buffer_descriptors
--WHERE bd.page_type IN (''DATA_PAGE'', ''INDEX_PAGE'')
GROUP BY database_id' + CASE WHEN @sqlmajorver >= 10 THEN ', numa_node' ELSE '' END + CASE WHEN @sqlmajorver >= 12 THEN ', is_in_bpool_extension' ELSE '' END + '
ORDER BY total_pages_MB DESC;'
		EXECUTE sp_executesql @sqlcmd;

This will just run the little section to determine the buffer pool consumers but now with  
an additional data conversion.
Normally you'll get just int values back from sys.dm_os_buffer_descriptors.  If this is fine I'll create a pull request.

Regards
Dirk

**Comment by DiHo78** [comment]
https://github.com/DiHo78/tigertoolbox/tree/patch-2/BPCheck

**Comment by 7gartner** [comment]
Dirk, I tested the code and it ran just fine.

**Comment by pmasl** [comment]
Thanks for the correction!
