### ISSUE TITLE
tls1.2/CheckClientUpdates.ps1 contains "smart quotes"

### ISSUE THREAD

**Issue by floppym** [Microsoft/tigertoolbox#51]
This script is completely broken at the moment.
```
At C:\Users\mgilbert\Desktop\temp\CheckClientUpdates.ps1:75 char:80
+ ... oft.win32.registrykey]::OpenRemoteBaseKey(â€˜LocalMachineâ€™, $env:CO ...
+                                                                 ~
Missing argument in parameter list.
```
Note the funky unicode quotes in place of the ASCII quotes that should be present.

**Comment by amitmsft** [comment]
How did you download this script file? I am looking at the code on in RAW format and I don't see any incorrect ASCII quotes. This is what I see:

if ($cli.DisplayVersion.Split(".")[2] -lt 4219 -and $cli.DisplayVersion.Split(".")[0] -eq 12)
        {
            Write-Host $cli.DisplayName "with version" $cli.DisplayVersion " needs to be updated to use TLS 1.2" -ForegroundColor Red
        }
        else

And what is the locale of your machine?

**Comment by floppym** [comment]
https://github.com/Microsoft/tigertoolbox/blob/master/tls1.2/CheckClientUpdates.ps1#L86

**Comment by floppym** [comment]
https://github.com/Microsoft/tigertoolbox/blob/master/tls1.2/CheckClientUpdates.ps1#L75

The incorrect quotes are clearly visible in Google Chrome.

**Comment by amitmsft** [comment]
Thanks. Corrected the formatting and submitted the changes. Could you please downloading the script and trying again.

**Comment by amitmsft** [comment]
I have closed this issue as fixed for now. Please add another issue if you find something new with the script.
