### ISSUE TITLE
The report definition has an invalid target namespace 'http://schemas.microsoft.com/sqlserver/reporting/2016/01/reportdefinition' which cannot be upgraded. 

### ISSUE THREAD

**Issue by RangaSQL** [Microsoft/tigertoolbox#53]
When trying to open a report under XEventReporting. The other "SQL Performance Baselinining Reports" worked great! I am very eager to see the XEvents reports :)

**Comment by amitmsft** [comment]
What is the version of target SQL Server instance that you are trying to run the reports against?

**Comment by francescovista** [comment]
I'm having a few trubles too, I have Visual Studio 2015 and SQL Server 2016. 
During the installation I set `TargetServerVersion = SQL Server 2016 or later `, is tigertoolbox compatible with these settings?

**Comment by savjani** [comment]
We have tested it with TargetServerVersion SQL Server 2012 and higher

**Comment by RangaSQL** [comment]
Microsoft SQL Server 2014 - 12.0.4100.1 (X64) 

Thanks for looking into this.

**Comment by RangaSQL** [comment]
Would love to see XEventReporting working and set it up on my servers. Thanks...

**Comment by Weimin496** [comment]
i have the same problem, it's old vb project, we just open and create report  by VS2015 or 2012. if we use vs2017 to open existing report or create new report, the report will not worked, throw exception:
The report definition is not valid.  Details: The report definition has an invalid target namespace 'http://schemas.microsoft.com/sqlserver/reporting/2010/01/reportdefinition' which cannot be upgraded.
