### ISSUE TITLE
The 'version_string' parameter is missing a value  

### ISSUE THREAD

**Issue by francescovista** [Microsoft/tigertoolbox#54]
This error was also mentioned at the bottom of the page on your "guide" [post](https://blogs.msdn.microsoft.com/sql_server_team/sql-server-performance-dashboard-reports-unleashed-for-enterprise-monitoring/).

I have to say that installing tigertoolbox is not straight forward. 

![value](https://user-images.githubusercontent.com/30395256/28556700-1fcbf8c4-715c-11e7-9d76-500df19db845.PNG)

**Comment by francescovista** [comment]
I set as report URL http://localhost/Reports

![reports](https://user-images.githubusercontent.com/30395256/28556799-b6dcf45c-715c-11e7-9ea0-902bfe8fa881.PNG)

**Comment by francescovista** [comment]
I setup that URL as TargetServerURL but when I deply I receive the error 

```
TITLE: Microsoft SQL Server Report Designer
------------------------------

Could not connect to the report server http://vlt218/Reports. Verify that the TargetServerURL is valid and that you have the correct permissions to connect to the report server.

------------------------------
ADDITIONAL INFORMATION:

Unable to connect to the remote server (System)

------------------------------

No connection could be made because the target machine actively refused it 172.17.16.227:443 (System)

------------------------------
BUTTONS:

OK
------------------------------

```
![error](https://user-images.githubusercontent.com/30395256/28556846-15650262-715d-11e7-9698-0f34d1703c3b.PNG)

**Comment by savjani** [comment]
try using http://localhost/reportserver or http://vlt218/reportserver

**Comment by francescovista** [comment]
Changed to http://vlt218/reportserver, same problem during installation as before an then if I open a report: 
![error](https://user-images.githubusercontent.com/30395256/28594579-9495c1ac-71e4-11e7-8b80-6c89e7791828.PNG)
