### ISSUE TITLE
Performance Dashboard not working with 20170418 Change to spGetPerfCountersFromPowerShell

### ISSUE THREAD

**Issue by LinkOps** [Microsoft/tigertoolbox#57]
There was a change to spGetPerfCountersFromPowerShell on the 18 April 2017 to handle named instances however this change is affecting the Perf Dashboard from being able to collect the performance counters as the performance counter list in the from sub query does not handle named instances and therefore does not match on any performance counters resulting in no data available. Doing an update on the PerformanceCounter table removing the injected instance name returns data on the perf dashboard

**Comment by LinkOps** [comment]
Surprisingly enough the script handles actual named instances fine but the problem becomes evident on default instances (MSSQLSERVER)

**Comment by savjani** [comment]
@LinkOps - I will look at the Powershell code. Meanwhile, can you use the xp_cmdshell or command line to collect perfmon jobs. Does that unblock you?
