### ISSUE TITLE
BPCheck sys.security_policies error on SQL 2008 & 2008 R2

### ISSUE THREAD

**Issue by yamezui** [Microsoft/tigertoolbox#58]
The following error occured when running BPCheck v2.2 on SQL Server 2008 and 2008R2:

-Starting Feature usage
**Msg 50000, Level 16, State 1, Line 1724
Feature usage subsection - Error raised in TRY block. Invalid object name 'sys.security_policies'.**

Of course Row Level Security Feature should be checked for SQL Server Major Version >= 13 (and not > 9 as in the script ).

**Comment by pmasl** [comment]
Should be fixed in the last couple versions. Thanks!
