### ISSUE TITLE
Where is the DacFx issues list?

### ISSUE THREAD

**Issue by StingyJack** [Microsoft/tigertoolbox#59]
There are problems with dacpac, bacpac, and visual studio that I need to report or have addressed and I cant find a web presence for those modules, I did try reporting them via Developer Community but the issues have been in status "Triaged" for months. Is there a different site or portal I should be using?

**Comment by amitmsft** [comment]
Please report them here: https://feedback.azure.com/forums/908035-sql-server

**Comment by StingyJack** [comment]
Thanks but I wasn't really looking for another void to speak into.

**Comment by amitmsft** [comment]
Hi Andrew,

We do review each and every feedback provided but address them as fixes or design changes in the product based on our prioritization exercise.

Could you point me to the links or issues that you had filed and I can forward that to the appropriate team?

Feedback taken about us being more proactive about responding to our feedback items.

Regards,
Amit Banerjee
LinkedIn<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fin.linkedin.com%2fpub%2famit-banerjee%2f20%2f64a%2f852&data=01%7c01%7camit.banerjee%40microsoft.com%7c547e7df7513448a8226908d3a6b9fcab%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=5oRtgGN3tfvuKSJPjsOHpg60%2fr8hQrvvR0SffYs%2bssw%3d> | Facebook<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.facebook.com%2fTroubleshootingSQL&data=01%7c01%7camit.banerjee%40microsoft.com%7c547e7df7513448a8226908d3a6b9fcab%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=rhG3cAjKeJL5%2fnq7vETev8Djf5HzInT8GWuGysQNCzI%3d> | Twitter<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2ftwitter.com%2fbanerjeeamit&data=01%7c01%7camit.banerjee%40microsoft.com%7c547e7df7513448a8226908d3a6b9fcab%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=FNs3I50wuhtQwq99F9YPaxXjUN3AvxpMUtOx%2bFB%2f%2fUw%3d> | TroubleshootingSQL<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.troubleshootingsql.com%2f&data=01%7c01%7camit.banerjee%40microsoft.com%7c547e7df7513448a8226908d3a6b9fcab%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=yg8hwzLC9X1eFY4kVoxYUKRQKFhQucEyxHmIB2t9yD8%3d>
Follow us on Twitter: @mssqltiger<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2ftwitter.com%2fmssqltiger&data=01%7c01%7camit.banerjee%40microsoft.com%7c547e7df7513448a8226908d3a6b9fcab%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=R9901KBBJUefMA0ih0XatUJ7lyyTCq4KPOCuyVRSfhI%3d> | Team Blog: Aka.ms/sqlserverteam<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2faka.ms%2fsqlserverteam&data=01%7c01%7camit.banerjee%40microsoft.com%7c547e7df7513448a8226908d3a6b9fcab%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=gvN1P32cTULsy3V1nGutsMi7wVrOg9K2VO9GbKCwxAA%3d>

**Comment by StingyJack** [comment]
I have these (at least. it was a quick search, not an exhaustive one)...

- https://developercommunity.visualstudio.com/content/problem/168913/there-doesnt-seem-to-be-anyone-left-on-the-ssdt-te.html
- https://developercommunity.visualstudio.com/content/problem/97061/153-sqlproj-not-supported.html
- https://developercommunity.visualstudio.com/content/problem/199941/i-cant-enable-any-do-not-drop-options-for-a-sqlpro.html
- https://developercommunity.visualstudio.com/content/problem/196517/new-cant-publish-sql-project-object-reference-not.html
- https://developercommunity.visualstudio.com/content/problem/118661/postdeployment-scripts-from-a-referenced-dacpac-do.html
- https://developercommunity.visualstudio.com/content/problem/169452/tfs-build-tasks-fail-without-error-for-sql-2016-ss.html
- https://developercommunity.visualstudio.com/content/problem/185781/attempting-to-publish-sqlproj-gives-null-ref-ex.html
- https://developercommunity.visualstudio.com/content/problem/185724/double-clicking-an-error-result-in-the-sql-query-r.html
- https://developercommunity.visualstudio.com/content/problem/185840/sql71502-warning-does-not-look-like-it-is-correct.html
- https://social.msdn.microsoft.com/Forums/sqlserver/en-US/ca69815b-f01b-442d-8b60-a46b8da7d721/why-is-publishing-a-dacpac-to-a-new-database-so-slow?forum=ssdt#ca69815b-f01b-442d-8b60-a46b8da7d721
- https://social.msdn.microsoft.com/Forums/sqlserver/en-US/df38a3c8-6ccc-40a7-94e7-175fb71b8a4b/where-is-the-response-if-unanswered-for-2-days-and-why-does-it-look-like-there-is-no-ssdt-team?forum=ssdt#df38a3c8-6ccc-40a7-94e7-175fb71b8a4b
- https://social.msdn.microsoft.com/Forums/sqlserver/en-US/c6b4550d-dfc6-4fd6-ac24-4564c46c8e86/error-msb4018-the-sqlmodelresolutiontask-task-failed-unexpectedly?forum=ssdt#c6b4550d-dfc6-4fd6-ac24-4564c46c8e86

**Comment by amitmsft** [comment]
Thanks. I will share the list with the appropriate team. I would request that for issues that you would like to see a design change, I would recommend filing a product feedback at https://feedback.azure.com/forums/908035-sql-server This GitHub repo or MSDN forums is not the right place to file that feedback.

**Comment by StingyJack** [comment]
I'm not sure any of them are change requests. Some are bugs, some are questions. 

For bugs and questions, is the avenue supposed to be either via the in VS feedback system or the MSDN forum?   I have more reported issues in the dev comm site, they should be tagged as "database" in the topics list.
