### ISSUE TITLE
Check_BP_Servers.sql

### ISSUE THREAD

**Issue by zensqlmonitor** [Microsoft/tigertoolbox#6]
Hi, 
Tkz for this script. There are 2 errors in the last commit:
- line 842: orphelan CREATE TABLE Info_
- line 4566:  FROM msdb.dbo.backupset WITH (NOLOCK) b is wrong, alias must be put after the table name -> FROM msdb.dbo.backupset b WITH (NOLOCK)

**Comment by MaftahHamza** [comment]
To avoid the Arithmetic overflow error converting varchar to data type numeric.

- Line 2557

replace :
IF @lpim = 0 AND @winver < 6.0 AND @arch = 64
By :
IF @lpim = 0 AND CAST(@winver AS DECIMAL(3,1)) < 6.0 AND @arch = 64

- Line 2888

replace :
IF @winver >= 6.0
By :
IF CAST(@winver AS DECIMAL(3,1))>= 6.0

**Comment by pmasl** [comment]
Fixed. Thanks!
