### ISSUE TITLE
Documentation for parameters is wrong. Options should be 1, not 0. 

### ISSUE THREAD

**Issue by spursrox** [Microsoft/tigertoolbox#63]
Documentation is wrong. All of the options examples have the same issue: The option should be 1, not 0. For example: 

@printCmds defaults to 0 (do not print all commands to screen) or optionally **0** (print all commands to screen). 

Should be: 
@printCmds defaults to 0 (do not print all commands to screen) or optionally **1** (print all commands to screen).

**Comment by pmasl** [comment]
Thanks you, fixed now.
