### ISSUE TITLE
This doesn't respect if an index uses data_compression on rebuild. 

### ISSUE THREAD

**Issue by d-moloney** [Microsoft/tigertoolbox#65]
The AdaptiveIndexDefrag  does not handle if  an index is setup to use data_compression =page (or row) this routine will remove the data_compression and rebuild without data_compression.

**Comment by pmasl** [comment]
Hi, this is fixed now. Please test the latest release 1.6.6

**Comment by d-moloney** [comment]
Thanks, taking a look now.  BTW: The README.MD page has a couple typos. Both descriptions indicate to use 0, I think one of them should be a 1 for each of these. 


@outputResults defaults to 0 (does not output fragmentation information) or optionally 0 (output fragmentation information after run completes).
@debugMode defaults to 0 (do not display debug comments) or optionally 0 (display debug comments)

**Comment by d-moloney** [comment]
There are a lot of discussions on the internet that indicate a reorganize doesn't update statistics.  If an index is reorganized shouldn't the statistics be updated after it is reorganized?  It doesn't appear that this script update statistics after a reorganize.

**Comment by d-moloney** [comment]
One more question, is there a way to force the data_compression on indexes that are not currently set to data_compression even if they don't meet the fragmentation levels?

**Comment by pmasl** [comment]
If indexes are reorganized rather than rebuilt, its stats are updated in a subsequent stats update step. Any option is only forced for any eligible index - this is primarily an index grooming proc. You can force a low threshold to make sure your indexes are all picked for a given database.
