### ISSUE TITLE
The procedure doesn't work

### ISSUE THREAD

**Issue by newhardwarefound** [Microsoft/tigertoolbox#66]
https://github.com/Microsoft/tigertoolbox/blob/140111f3c95339a8d510dbb59b7c24a9dcc470c7/change-tracking/ChangeTrackingCleanup.sql#L15

It returned the error message saying that change tracking hasn't been enabled on that table. But when I try to enable CT on that table, it prompts me that CT has already been enabled on that table. Mine is Sql server 2016 SP1.

**Comment by amitmsft** [comment]
If you are still facing this issue, I would recommend opening a support incident with CSS to troubleshoot this as this is a procedure that is shipped with the product and fully supported by CSS.
