### ISSUE TITLE
Parameter @tblName doesn't work 

### ISSUE THREAD

**Issue by arhipovdv** [Microsoft/tigertoolbox#70]
Exce proc like this:
EXEC dbo.usp_AdaptiveIndexDefrag @dbScope = 'SomeDataBase', @tblName = 'dbo.SomeTable', @onlineRebuild = 1, @dealLOB=1 , @printCmds = 1,  @debugMode = 1	
but in messages i see that proceeds all tables, not just one from params:
![image](https://user-images.githubusercontent.com/9361966/36489513-460e5b04-1737-11e8-915f-2598e683cc80.png)

**Comment by pmasl** [comment]
I cannot repro. See below for command:

EXEC dbo.usp_AdaptiveIndexDefrag @dbScope = 'sqlnexus', @tblName = 'dbo.CounterData', @onlineRebuild = 1, @dealLOB=1 , @printCmds = 1, @debugmode = 1

Validating options...
Scope has changed. Forcing rescan of single database in scope...
Starting up...

Executing AdaptiveIndexDefrag v1.6.6.5 on Microsoft SQL Server 2016 (SP2-CU3) (KB4458871) - 13.0.5216.0 (X64) 
	Sep 13 2018 22:16:01 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)

The selected parameters are:
Defragment indexes with fragmentation greater or equal to 5;
Rebuild indexes with fragmentation greater than 30;
Rebuild columnstore indexes with fragmentation greater than 10;
Defragment ALL indexes;
Commands WILL be executed automatically;
Defragment indexes in DESC order of the RANGE_SCAN_COUNT value;
Time limit was specified and is 480 minutes;
The [sqlnexus] database will be defragmented;
The dbo.CounterData table will be defragmented;
We WILL be rescanning indexes;
The scan will be performed in LIMITED mode;
LOBs will NOT be compacted;
Limit defrags to indexes with more than 8 pages;
Indexes will be defragmented ONLINE;
Indexes will be sorted in the DATABASE;
Indexes will use CURRENT compression setting;
Indexes will keep its EXISTING Fill Factor;		
Only the right-most populated partitions will be considered if greater than 8 page(s);
Statistics WILL be updated on all stats belonging to parent table;
Statistics will be updated using a calculated threshold similar to TF2371 on tables.
Statistics will be updated with Incremental property (if any) not changed from current setting.
Defragmentation will use system defaults for processors;
Lock timeout is set to system default for offline rebuilds;
Starting with SQL Server 2014, lock timeout is set to 5 for online rebuilds;
Starting with SQL Server 2014, lock timeout action is set to SELF for online rebuilds;
 DO print the sql commands;
 DO NOT output fragmentation levels;
Wait 00:00:05 (hh:mm:ss) between index operations;
Execute in DEBUG mode.

Listing databases...
Retrieving list of databases to loop, excluding Always On secondary replicas...
Cross checking with exceptions for today...
Preparing for new database scan...
Scanning database(s)...
 Looping through list of databases and checking for fragmentation...
  Working on database [sqlnexus]...
   Building list of objects in database...
    Setting partition handling...
      Setting only right-most populated partition...
      Filtering indexes according to ixtypeOption parameter...
    Getting rowstore indexes...
      Analyzing index ID 1 on table [CounterData]...
    Getting columnstore indexes...
    Looking up additional index information...
    Looking up additional statistic information...
 Listing and removing disabled indexes (except those disabled by the defrag cycle itself) or hypothetical indexes from loop...
 Updating Exception mask for any index that has a restriction on the days it CANNOT be defragmented...
Looping through batch list... There are 1 indexes to defragment in 1 database(s)!
Looping through batch list... There are 1 index related statistics to update in 1 database(s), plus 3 other statistics to update in 1 database(s)!
 Selecting an index to defragment...
  Getting partition count...
  Getting selected index information...
  Checking if any LOBs exist...
  Checking for Columnstore index...
  Checking if index does not allow page locks...
    Found 99.1866 percent fragmentation on index [PK__CounterD__1FB2147B792B082C]...
  Building SQL statements...
 Updating all other unhandled statistics using finer thresholds (if any)...
   Selecting a statistic to update...
   Getting information on selected statistic...
   Determining modification row counter for statistic [_WA_Sys_00000003_7DD8979A] on table or view [CounterData] of DB [sqlnexus]...
     Using sys.dm_db_stats_properties DMF...
     Found a row modification counter of 0.000 and 618258 rows...
     No need to update statistic [_WA_Sys_00000003_7DD8979A] on DB [sqlnexus] and object [CounterData]...
   Selecting a statistic to update...
   Getting information on selected statistic...
   Determining modification row counter for statistic [_WA_Sys_00000002_7DD8979A] on table or view [CounterData] of DB [sqlnexus]...
     Using sys.dm_db_stats_properties DMF...
     Found a row modification counter of 0.000 and 618258 rows...
     No need to update statistic [_WA_Sys_00000002_7DD8979A] on DB [sqlnexus] and object [CounterData]...
   Selecting a statistic to update...
   Getting information on selected statistic...
   Determining modification row counter for statistic [_WA_Sys_00000004_7DD8979A] on table or view [CounterData] of DB [sqlnexus]...
     Using sys.dm_db_stats_properties DMF...
     Found a row modification counter of 0.000 and 618258 rows...
     No need to update statistic [_WA_Sys_00000004_7DD8979A] on DB [sqlnexus] and object [CounterData]...
 No remaining statistics to update...
 Reseting working table statuses.
 Dropping temporary objects
All done!

**Comment by KonnectSalon** [comment]
Run this:

		Truncate table tbl_AdaptiveIndexDefrag_Working
		Truncate table tbl_AdaptiveIndexDefrag_Stats_Working
		Truncate table tbl_AdaptiveIndexDefrag_Stats_log
		Truncate table tbl_AdaptiveIndexDefrag_log
		Truncate table tbl_AdaptiveIndexDefrag_IxDisableStatus
		Truncate table tbl_AdaptiveIndexDefrag_Exceptions
		Truncate table tbl_AdaptiveIndexDefrag_Analysis_log

Then it will work as expected
