### ISSUE TITLE
Invalid column name 'data_compression_desc'.

### ISSUE THREAD

**Issue by pvcardoso** [Microsoft/tigertoolbox#75]
Microsoft SQL Server Enterprise Edition (64-bit)
Microsoft Windows NT 6.0 (6002)
9.00.4060.00 (I know !!!!!)

AdaptiveIndexDefrag: Version: v1.6.6.2 - 2/24/2018

The following error occours executing:
EXEC dbo.usp_AdaptiveIndexDefrag @onlineRebuild = 1,  @timeLimit = 240, @statsSample = 'FULLSCAN'

Message
Executed as user: NT AUTHORITY\SYSTEM. Scope has changed. Forcing rescan... [SQLSTATE 01000] (Message 50000)  Error 207 has occurred. Message: Invalid column name 'data_compression_desc'. (Line Number: 2) [SQLSTATE 01000] (Message 50000).  The step succeeded.

----------------
Workaround:
Comment (Line 1301)
--, [compression_type] = [data_compression_desc]

**Comment by pmasl** [comment]
Thank you for your correction!
