### ISSUE TITLE
Message: Cannot insert the value NULL into column 'objectID', table 'msdb.dbo.tbl_AdaptiveIndexDefrag_Stats_log'; column does not allow nulls. INSERT fails. (Line Number: 2475)

### ISSUE THREAD

**Issue by pvcardoso** [Microsoft/tigertoolbox#76]
Microsoft SQL Server Standard (64-bit)
Microsoft Windows NT 6.1 (7601)
SQL: 11.0.3128.0

AdaptiveIndexDefrag: Version: v1.6.6.2 - 2/24/2018

When executing the command:
EXEC dbo.usp_AdaptiveIndexDefrag @onlinerebuild = 1, @Timelimit = 240, @statssample = 'FULLSCAN'

Message:
Error 515 has occurred. Message: Cannot insert the value NULL into column 'objectID', table 'msdb.dbo.tbl_AdaptiveIndexDefrag_Stats_log'; column does not allow nulls. INSERT fails. (Line Number: 2475)

**Comment by pmasl** [comment]
I cannot repro this. Have you used a more recent version, and if so, is this still ongoing?
Thank you
