### ISSUE TITLE
Running EXEC dbo.usp_AdaptiveIndexDefrag on SQL 2005 takes 15 seconds and do nothing

### ISSUE THREAD

**Issue by AlexBAFonseca** [Microsoft/tigertoolbox#77]
Hi,

Can you help me whit the subject ?

Have one SQL 2005 instance that runs  dbo.usp_AdaptiveIndexDefrag every night with no parameters, but only takes 15 seconds and always less than one minute.
The resident databases are not in shape to justifie this behavior.
If we implement the SP with the option "SET @deploymode = 0", the next night it works every 8 hours by default.
The nigth after we have the same behavior.

Can you advise one specific version to run with SQL 2005? Any thoughts?

Thank you very much.

Regards

Alex.

**Comment by pmasl** [comment]
Does this still occur? SQL Server 2005 is no longer supported. That being said, let me know if this still occurs and what build you are using. I can investigate this post-Ignite and get back to you.

**Comment by pmasl** [comment]
No response, closing issue
