### ISSUE TITLE
Overflow error at SQLPerformanceBaseline/SystemHealthSession/sploadsecurityringbuffer

### ISSUE THREAD

**Issue by ikdonev** [Microsoft/tigertoolbox#8]
On systems with a lot of security errors sploadsecurityringbuffer is throwing an overflow error on the integer [id] columns. Changing it to bigint does the job.

**Comment by amitmsft** [comment]
Thanks for reporting this. We will correct it.

**Comment by savjani** [comment]
Hi Ivan,

Did you download the file from latest branch since we have already fixed it. the id column is bigint. I would suggest you recreate the stored procedure using the code below.


Create procedure [dbo].[spLoadConnectivity_ring_buffer]

@UTDDateDiff int

as

if object_id('tbl_connectivity_ring_buffer') is not null

drop table tbl_connectivity_ring_buffer



  select 

   c1.value('(./event/@timestamp)[1]', 'datetime') as utctimestamp,

  	DATEADD(mi,@UTDDateDiff,c1.value('(./event/@timestamp)[1]', 'datetime')) as [timestamp],

              c1.value('(./event/data[@name="type"]/text)[1]', 'varchar(100)') AS [Type],

              c1.value('(./event/data[@name="id"]/value)[1]', 'bigint') as record_id,

			  c1.value('(./event/data[@name="source"]/text)[1]', 'varchar(20)') as source,

			  c1.value('(./event/data[@name="session_id"]/value)[1]', 'int') as session_id,

			  c1.value('(./event/data[@name="os_error"]/value)[1]', 'bigint') as os_error,

			  c1.value('(./event/data[@name="sni_error"]/value)[1]', 'bigint') as sni_error,

			  c1.value('(./event/data[@name="sni_consumer_error"]/value)[1]', 'bigint') as sni_consumer_error,

			  c1.value('(./event/data[@name="state"]/value)[1]', 'int') as [state],

			  c1.value('(./event/data[@name="port"]/value)[1]', 'int') as port,

			  c1.value('(./event/data[@name="remote_port"]/value)[1]', 'int') as remote_port,

			  c1.value('(./event/data[@name="tds_input_buffer_error"]/value)[1]', 'bigint') as tds_inputbuffererror,

			  c1.value('(./event/data[@name="total_login_time_ms"]/value)[1]', 'bigint') as total_login_time_ms,

			  c1.value('(./event/data[@name="login_task_enqueued_ms"]/value)[1]', 'bigint') as login_task_enqueued_ms,

			  c1.value('(./event/data[@name="network_writes_ms"]/value)[1]', 'bigint') as network_writes_ms,

			  c1.value('(./event/data[@name="network_reads_ms"]/value)[1]', 'bigint') as network_reads_ms,

			  c1.value('(./event/data[@name="ssl_processing_ms"]/value)[1]', 'bigint') as ssl_processing_ms,

			  c1.value('(./event/data[@name="sspi_processing_ms"]/value)[1]', 'bigint') as sspi_processing_ms,

			  c1.value('(./event/data[@name="login_trigger_and_resource_governor_processing_ms"]/value)[1]', 'bigint') as login_trigger_and_resource_governor_processing_ms,

			  c1.value('(./event/data[@name="connection_id"]/value)[1]', 'varchar(50)') as connection_id,

			  c1.value('(./event/data[@name="connection_peer_id"]/value)[1]', 'varchar(50)') as connection_peer_id,

			  c1.value('(./event/data[@name="local_host"]/value)[1]', 'varchar (50)') as local_host,

			  c1.value('(./event/data[@name="remote_host"]/value)[1]', 'varchar (50)') as remote_host,

			  c1.value('(./event/data[@name="SessionIsKilled"]/value)[1]', 'smallint') as SessionIsKilled

	into tbl_connectivity_ring_buffer

	from tbl_XEImport where  object_name =  'connectivity_ring_buffer_recorded'              



GO

**Comment by ikdonev** [comment]
Thanks for the update. 
I think we are talking for different SPs here. I am referring to SpLoadSecurityRingBuffer (tigertoolbox/SQL-Performance-Baseline/CreateSystemhealthDBAndSchema.sql, line 577).

**Comment by amitmsft** [comment]
It is already set to bigint. Could you please check if you are looking at an older fork or sync?

 utctimestamp,

			DATEADD(mi,@UTDDateDiff,c1.value('(./event/@timestamp)[1]', 'datetime')) as [timestamp],

			**_c1.value('(./event/data[@name="id"])[1]', 'bigint') as id,_**

**Comment by savjani** [comment]
My bad and Thank you for reporting this. I have fixed the SpLoadSecurityRingBuffer and changed the datatype to bigint. Can you resync and confirm. Thanks !!!
