### ISSUE TITLE
usp_AdaptiveIndexDefrag debug mode error with convert of rows

### ISSUE THREAD

**Issue by d-moloney** [Microsoft/tigertoolbox#87]
I have a very large table with 21,308,738,688 rows and when debug_mode is on there is an issue the below line of code

     Error 8115 has occurred. Message: Arithmetic overflow error converting expression to data type nvarchar. (Line Number: 2298)

				IF @debugMode = 1
				BEGIN
					SELECT @debugMessage = '     Found a row modification counter of ' + CONVERT(NVARCHAR(10), @rowmodctr) + ' and ' + CONVERT(NVARCHAR(10), CASE WHEN @rows IS NOT NULL AND @rows < @record_count THEN @rows ELSE @record_count END) + ' rows' + CASE WHEN @stats_isincremental = 1 THEN ' on partition ' + CONVERT(NVARCHAR(10), @partitionNumber) ELSE '' END + '...';
					RAISERROR(@debugMessage, 0, 42) WITH NOWAIT;
					--select @debugMessage
				END

These need to be NVARCHAR(11)

**Comment by pmasl** [comment]
Done and will be merged in a few minutes. Thank you!
