### ISSUE TITLE
exec usp_AdaptiveIndexDefrag major error

### ISSUE THREAD

**Issue by d-moloney** [Microsoft/tigertoolbox#91]
There is a major error with this version without fixing this code, any table that is compressed will become uncompressed. 

There are two missing 
	EXECUTE sp_executesql @updateSQL;
statements. 
the correct code should be.

				IF @scanMode = 'LIMITED'
				BEGIN
					IF @sqlmajorver = 9
					BEGIN
						SELECT @updateSQL = N'UPDATE ids
	SET [record_count] = [rows], [compression_type] = N''''
	FROM [' + DB_NAME(@AID_dbID) + '].dbo.tbl_AdaptiveIndexDefrag_Working ids WITH (NOLOCK)
	INNER JOIN [' + DB_NAME(@dbID) + '].sys.partitions AS p WITH (NOLOCK) ON ids.objectID = p.[object_id] AND ids.indexID = p.index_id AND ids.partitionNumber = p.partition_number
	WHERE ids.[dbID] = ' + CAST(@dbID AS NVARCHAR(10));
		EXECUTE sp_executesql @updateSQL;
					END
					ELSE
					BEGIN
						SELECT @updateSQL = N'UPDATE ids
	SET [record_count] = [rows], [compression_type] = [data_compression_desc] END
	FROM [' + DB_NAME(@AID_dbID) + '].dbo.tbl_AdaptiveIndexDefrag_Working ids WITH (NOLOCK)
	INNER JOIN [' + DB_NAME(@dbID) + '].sys.partitions AS p WITH (NOLOCK) ON ids.objectID = p.[object_id] AND ids.indexID = p.index_id AND ids.partitionNumber = p.partition_number
	WHERE ids.[dbID] = ' + CAST(@dbID AS NVARCHAR(10));
		EXECUTE sp_executesql @updateSQL;
					END
				end

**Comment by pmasl** [comment]
I see you fixed the issue and it was merged. thank you.
