### ISSUE TITLE
[AdaptiveIndexDefrag] Arithmetic overflow while determining modification row counter for statistic on table or view

### ISSUE THREAD

**Issue by CodyFitzpatrick** [Microsoft/tigertoolbox#99]
First off, thank you for creating this script. It is a massive time saver.

To the issue: I ran v1.6.6.5 of `AdaptiveIndexDefrag` on Microsoft SQL Server 2012 last night on a database with over 1k tables. About 2 hours in (and ~4900 lines into the debug log), the script threw the following error:

```
Determining modification row counter for statistic [_WA_Sys_0000001D_020B1573] on table or view [MY_TABLE_NAME] of DB [MY_DATABASE_NAME]...
     Using sys.dm_db_stats_properties DMF...
     Error 8115 has occurred. Message: Arithmetic overflow error converting expression to data type nvarchar. (Line Number: 2347)
```

I believe this is an error similar to that which was solved in issue #87, but I am admittedly not a SQL expert and would rather leave the crafting of a potential solution to someone who can craft an efficient and stable one.

**Comment by pmasl** [comment]
Hi Cody, thank you for finding this. I believe the issue is indeed with a second missed occurrence in the code with #87 not your suggestion. The reported line is a debug only occurrence. Do you have any issues if not running debug flag? I just pushed a fix for line 2347, and let me know if you get an exception somewhere else.

**Comment by CodyFitzpatrick** [comment]
@pmasl Thanks for looking into this and for already pushing a fix! I'm going to run the script in debug mode at first on the same database & table to see if this error shows its face again. If it does, I'll then try with debug mode off. Will report back here either way. Thanks again!

**Comment by CodyFitzpatrick** [comment]
@pmasl I'm sorry for the delayed response. Your fix worked, even in debug mode. Thanks again for that!
